//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarouselSlide
    {
        public System.Guid CarouselId { get; set; }
        public System.Guid SlideId { get; set; }
        public int SortIndex { get; set; }
    
        public virtual Carousel Carousel { get; set; }
        public virtual Slide Slide { get; set; }
    }
}
