//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinistryService
    {
        public System.Guid MinistryId { get; set; }
        public int SortIndex { get; set; }
        public string LinkText { get; set; }
        public string LinkUrl { get; set; }
    
        public virtual Ministry Ministry { get; set; }
    }
}
