//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsReleaseLanguage
    {
        public System.Guid ReleaseId { get; set; }
        public int LanguageId { get; set; }
        public string Location { get; set; }
        public string Summary { get; set; }
        public string SocialMediaSummary { get; set; }
        public string SocialMediaHeadline { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual NewsRelease Release { get; set; }
    }
}
