//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsReleaseDocument
    {
        public NewsReleaseDocument()
        {
            this.Languages = new HashSet<NewsReleaseDocumentLanguage>();
            this.Contacts = new HashSet<NewsReleaseDocumentContact>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ReleaseId { get; set; }
        public int SortIndex { get; set; }
        public PageLayout PageLayout { get; set; }
    
        public virtual NewsRelease Release { get; set; }
        public virtual ICollection<NewsReleaseDocumentLanguage> Languages { get; set; }
        public virtual ICollection<NewsReleaseDocumentContact> Contacts { get; set; }
    }
}
