//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsReleaseImage
    {
        public NewsReleaseImage()
        {
            this.Languages = new HashSet<NewsReleaseImageLanguage>();
            this.DocumentLanguages = new HashSet<NewsReleaseDocumentLanguage>();
            this.NewsReleaseTypes = new HashSet<NewsReleaseType>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string MimeType { get; set; }
        public int SortOrder { get; set; }
        public System.Guid BlobId { get; set; }
    
        public virtual ICollection<NewsReleaseImageLanguage> Languages { get; set; }
        public virtual Blob Blob { get; set; }
        public virtual ICollection<NewsReleaseDocumentLanguage> DocumentLanguages { get; set; }
        public virtual ICollection<NewsReleaseType> NewsReleaseTypes { get; set; }
    }
}
