//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsRelease
    {
        public NewsRelease()
        {
            this.Languages = new HashSet<NewsReleaseLanguage>();
            this.Ministries = new HashSet<Ministry>();
            this.Sectors = new HashSet<Sector>();
            this.Logs = new HashSet<NewsReleaseLog>();
            this.History = new HashSet<NewsReleaseHistory>();
            this.Documents = new HashSet<NewsReleaseDocument>();
            this.Tags = new HashSet<Tag>();
            this.TopMinistries = new HashSet<Ministry>();
            this.FeatureMinistries = new HashSet<Ministry>();
            this.TopSectors = new HashSet<Sector>();
            this.FeatureSectors = new HashSet<Sector>();
            this.FeatureThemes = new HashSet<Theme>();
            this.TopThemes = new HashSet<Theme>();
            this.Themes = new HashSet<Theme>();
            this.MediaDistributionLists = new HashSet<MediaDistributionList>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTimeOffset Timestamp { get; set; }
        public string Key { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> YearRelease { get; set; }
        public Nullable<System.Guid> MinistryId { get; set; }
        public Nullable<int> MinistryRelease { get; set; }
        public string Reference { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public Nullable<System.DateTime> ReleaseDateTime { get; set; }
        public Nullable<System.DateTimeOffset> PublishDateTime { get; set; }
        public bool IsPublished { get; set; }
        public PublishOptions PublishOptions { get; set; }
        public bool IsActive { get; set; }
        public System.Guid CollectionId { get; set; }
        public bool IsCommitted { get; set; }
        public string AtomId { get; set; }
        public string Keywords { get; set; }
        public string AssetUrl { get; set; }
        public bool HasMediaAssets { get; set; }
        public ReleaseType ReleaseType { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<int> NodSubscribers { get; set; }
        public Nullable<int> MediaSubscribers { get; set; }
    
        public virtual ICollection<NewsReleaseLanguage> Languages { get; set; }
        public virtual ICollection<Ministry> Ministries { get; set; }
        public virtual ICollection<Sector> Sectors { get; set; }
        public virtual ICollection<NewsReleaseLog> Logs { get; set; }
        public virtual Ministry Ministry { get; set; }
        public virtual ICollection<NewsReleaseHistory> History { get; set; }
        public virtual ICollection<NewsReleaseDocument> Documents { get; set; }
        public virtual NewsReleaseCollection Collection { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Ministry> TopMinistries { get; set; }
        public virtual ICollection<Ministry> FeatureMinistries { get; set; }
        public virtual ICollection<Sector> TopSectors { get; set; }
        public virtual ICollection<Sector> FeatureSectors { get; set; }
        public virtual ICollection<Theme> FeatureThemes { get; set; }
        public virtual ICollection<Theme> TopThemes { get; set; }
        public virtual ICollection<Theme> Themes { get; set; }
        public virtual ICollection<MediaDistributionList> MediaDistributionLists { get; set; }
    }
}
