//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsReleaseType
    {
        public string PageTitle { get; set; }
        public int LanguageId { get; set; }
        public int ReleaseType { get; set; }
        public int SortOrder { get; set; }
        public int PageLayout { get; set; }
        public Nullable<System.Guid> PageImageId { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual NewsReleaseImage PageImage { get; set; }
    }
}
