//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsReleaseImageLanguage
    {
        public NewsReleaseImageLanguage()
        {
            this.DocumentLanguages = new HashSet<NewsReleaseDocumentLanguage>();
        }
    
        public System.Guid ImageId { get; set; }
        public int LanguageId { get; set; }
        public string AlternateName { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual NewsReleaseImage Image { get; set; }
        public virtual ICollection<NewsReleaseDocumentLanguage> DocumentLanguages { get; set; }
    }
}
