//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.Data.Entity
{
    using System;
    
    [Flags]
    public enum PublishOptions : int
    {
        PublishNewsArchives = 1,
        PublishNewsOnDemand = 2,
        PublishMediaContacts = 4
    }
}
