CREATE TABLE [media].[MediaRequest] (
    [Id]                 UNIQUEIDENTIFIER   CONSTRAINT [DF_MediaRequest_Id] DEFAULT (newid()) NOT NULL,
    [CreatedAt]          DATETIMEOFFSET (7) NOT NULL,
    [CreatedById]        INT   NOT NULL,
    [ModifiedAt]         DATETIMEOFFSET (7) NOT NULL,
    [ModifiedById]       INT   NOT NULL,
    [LeadMinistryId]     UNIQUEIDENTIFIER   NOT NULL,
    [ResponsibleUserId]  INT   NOT NULL,
    [DeadlineAt]         DATETIMEOFFSET (7) NULL,
    [RequestTopic]       NVARCHAR(250)      CONSTRAINT [DF_MediaRequest_Subject] DEFAULT ('') NOT NULL,
    [RequestContent]     NVARCHAR(4000)     CONSTRAINT [DF_MediaRequest_Content] DEFAULT ('') NOT NULL,
    [Response]           NVARCHAR(MAX)     CONSTRAINT [DF_MediaRequest_Response] DEFAULT ('') NOT NULL,
    [IsActive]           BIT NOT NULL DEFAULT 1,
    [RequestedAt]        DATETIMEOFFSET (7) NOT NULL,
    [AcknowledgedAt]     DATETIMEOFFSET (7) NULL,
    [RespondedAt]        DATETIMEOFFSET (7) NULL,
    [RequestParentId]    UNIQUEIDENTIFIER   NULL,
    [EodReportWith] INT NULL , 
    [ResolutionId] UNIQUEIDENTIFIER NULL, 
    [TakeOverRequestMinistryId] UNIQUEIDENTIFIER NULL, 
    CONSTRAINT [PK_MediaRequest] PRIMARY KEY CLUSTERED ([Id] ASC),  
    CONSTRAINT [FK_MediaRequest_Ministry] FOREIGN KEY ([LeadMinistryId]) REFERENCES [dbo].[Ministry]([Id]), 
    CONSTRAINT [FK_MediaRequest_SystemUser] FOREIGN KEY ([ResponsibleUserId]) REFERENCES [calendar].[SystemUser]([Id]), 
    CONSTRAINT [FK_MediaRequest_Parent] FOREIGN KEY ([RequestParentId]) REFERENCES [media].[MediaRequest]([Id]),
    CONSTRAINT [FK_MediaRequest_SystemUser_Created] FOREIGN KEY ([CreatedById]) REFERENCES [calendar].[SystemUser]([Id]),
    CONSTRAINT [FK_MediaRequest_SystemUser_Modified] FOREIGN KEY ([ModifiedById]) REFERENCES [calendar].[SystemUser]([Id]), 
    CONSTRAINT [Response] CHECK (([Response] = '' AND [RespondedAt] IS NULL) OR NOT ([Response] = '' OR [RespondedAt] IS NULL)), 
    CONSTRAINT [FK_MediaRequest_MediaRequestResolution] FOREIGN KEY ([ResolutionId]) REFERENCES [MediaRequestResolution]([Id]),
    CONSTRAINT [FK_MediaRequest_TakeOverRequestMinistry] FOREIGN KEY ([TakeOverRequestMinistryId]) REFERENCES [dbo].[Ministry] ([Id])
);