//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaRelationsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactAddresses = new HashSet<ContactAddress>();
            this.ContactBeats = new HashSet<ContactBeat>();
            this.ContactMediaJobTitles = new HashSet<ContactMediaJobTitle>();
            this.ContactPhoneNumbers = new HashSet<ContactPhoneNumber>();
            this.ContactWebAddresses = new HashSet<ContactWebAddress>();
            this.ElectoralDistricts = new HashSet<ElectoralDistrict>();
            this.Regions = new HashSet<Region>();
            this.Sectors = new HashSet<Sector>();
            this.MediaRequestContacts = new HashSet<MediaRequestContact>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.Guid> MinistryId { get; set; }
        public Nullable<System.Guid> MinisterialJobTitleId { get; set; }
        public Nullable<System.Guid> MLAAssignmentId { get; set; }
        public bool IsPressGallery { get; set; }
        public bool HasMinisterAssignment { get; set; }
        public bool IsPrimaryMediaContact { get; set; }
        public bool IsSecondaryMediaContact { get; set; }
        public bool IsActive { get; set; }
        public string RecordEditedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ShowNotes { get; set; }
    
        public virtual ICollection<ContactAddress> ContactAddresses { get; set; }
        public virtual ElectoralDistrict ElectoralDistrict { get; set; }
        public virtual MinisterialJobTitle MinisterialJobTitle { get; set; }
        public virtual ICollection<ContactBeat> ContactBeats { get; set; }
        public virtual ICollection<ContactMediaJobTitle> ContactMediaJobTitles { get; set; }
        public virtual ICollection<ContactPhoneNumber> ContactPhoneNumbers { get; set; }
        public virtual ICollection<ContactWebAddress> ContactWebAddresses { get; set; }
        public virtual ICollection<ElectoralDistrict> ElectoralDistricts { get; set; }
        public virtual Ministry Ministry { get; set; }
        public virtual ICollection<Region> Regions { get; set; }
        public virtual ICollection<Sector> Sectors { get; set; }
        public virtual ICollection<MediaRequestContact> MediaRequestContacts { get; set; }
    }
}
