//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaRelationsDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediaRelationsEntities : DbContext
    {

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Beat> Beats { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyAddress> CompanyAddresses { get; set; }
        public DbSet<CompanyPhoneNumber> CompanyPhoneNumbers { get; set; }
        public DbSet<CompanyWebAddress> CompanyWebAddresses { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<ContactAddress> ContactAddresses { get; set; }
        public DbSet<ContactBeat> ContactBeats { get; set; }
        public DbSet<ContactMediaJobTitle> ContactMediaJobTitles { get; set; }
        public DbSet<ContactPhoneNumber> ContactPhoneNumbers { get; set; }
        public DbSet<ContactWebAddress> ContactWebAddresses { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Distribution> Distributions { get; set; }
        public DbSet<ElectoralDistrict> ElectoralDistricts { get; set; }
        public DbSet<Ethnicity> Ethnicities { get; set; }
        public DbSet<MediaDesk> MediaDesks { get; set; }
        public DbSet<MediaJobTitle> MediaJobTitles { get; set; }
        public DbSet<MediaType> MediaTypes { get; set; }
        public DbSet<MinisterialJobTitle> MinisterialJobTitles { get; set; }
        public DbSet<PhoneType> PhoneTypes { get; set; }
        public DbSet<PrintCategory> PrintCategories { get; set; }
        public DbSet<ProvState> ProvStates { get; set; }
        public DbSet<PublicationDay> PublicationDays { get; set; }
        public DbSet<PublicationFrequency> PublicationFrequencies { get; set; }
        public DbSet<Report> Reports { get; set; }
        public DbSet<SpecialtyPublication> SpecialtyPublications { get; set; }
        public DbSet<SysConfig> SysConfigs { get; set; }
        public DbSet<SysLog> SysLogs { get; set; }
        public DbSet<WebAddressType> WebAddressTypes { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Ministry> Ministries { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Sector> Sectors { get; set; }
        public DbSet<MediaRequest> MediaRequests { get; set; }
        public DbSet<MediaRequestContact> MediaRequestContacts { get; set; }
    }
}
