//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaRelationsDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLog
    {
        public int LogID { get; set; }
        public string Action { get; set; }
        public string EntityType { get; set; }
        public Nullable<System.Guid> EntityId { get; set; }
        public string EntityData { get; set; }
        public Nullable<System.Guid> EventId { get; set; }
        public string EventData { get; set; }
        public string EventUser { get; set; }
        public System.DateTime EventDate { get; set; }
    }
}
