//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gcpe.Hub.News.ReleaseManagement {
    
    
    public partial class Default {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Gcpe.Hub.News.ReleaseManagement.ReleaseManagement Master {
            get {
                return ((Gcpe.Hub.News.ReleaseManagement.ReleaseManagement)(base.Master));
            }
        }
    }
}
