// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Gcpe.Hub.Services.Legacy.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Article
    {
        /// <summary>
        /// Initializes a new instance of the Article class.
        /// </summary>
        public Article()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Article class.
        /// </summary>
        public Article(string id = default(string), string uri = default(string), string title = default(string), string htmlContent = default(string), string textContent = default(string), System.DateTimeOffset? published = default(System.DateTimeOffset?), IList<string> distributionLists = default(IList<string>))
        {
            Id = id;
            Uri = uri;
            Title = title;
            HtmlContent = htmlContent;
            TextContent = textContent;
            Published = published;
            DistributionLists = distributionLists;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Uri")]
        public string Uri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HtmlContent")]
        public string HtmlContent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TextContent")]
        public string TextContent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Published")]
        public System.DateTimeOffset? Published { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistributionLists")]
        public IList<string> DistributionLists { get; set; }

    }
}
