USE [master]
GO

IF EXISTS(select * from sys.databases where name='Gcpe.Hub')
DROP DATABASE [Gcpe.Hub]
GO

/****** Object:  Database [Gcpe.Hub]    Script Date: 2018-10-30 9:51:06 AM ******/
CREATE DATABASE [Gcpe.Hub]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Gcpe.Hub', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Gcpe.Hub.mdf' , SIZE = 2956480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Gcpe.Hub_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Gcpe.Hub_Log.ldf' , SIZE = 265344KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Gcpe.Hub] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Gcpe.Hub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Gcpe.Hub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET ARITHABORT OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Gcpe.Hub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Gcpe.Hub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Gcpe.Hub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Gcpe.Hub] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Gcpe.Hub] SET  MULTI_USER 
GO

ALTER DATABASE [Gcpe.Hub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Gcpe.Hub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Gcpe.Hub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Gcpe.Hub] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Gcpe.Hub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Gcpe.Hub] SET  READ_WRITE 
GO


