USE [Gcpe.Hub]
GO

-- See the gcpe.hub-data-01-dbo-required script.
DECLARE @hqMinistryId uniqueidentifier = N'321d9c68-96ba-417b-bb89-78c7ce275458'; 
DECLARE @hqMinistryShortName varchar(10) = N'GCPEHQ';
DECLARE @hqMinistryDisplayName varchar(255) = N'GCPE HQ';


INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (@hqMinistryId, @hqMinistryId, 180, @hqMinistryDisplayName, @hqMinistryShortName, 1, N'', N'', N'', CAST(N'2016-10-27T19:30:07.973' AS DateTime), N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'', N'', NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, N'')

INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (N'768dbf29-89c6-48d1-901e-017a8a3557a4', N'768DBF29-89C6-48D1-901E-017A8A3557A4', 190, N'GCPE Media Relations', N'GCPEMEDIA', 1, N'', N'', N'', CAST(N'2016-10-27T19:30:07.973' AS DateTime), N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'', N'', NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, N'')

INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (N'aae302f1-05e1-4df9-8df3-1e4dd557278d', N'office-of-the-premier', 0, N'Office of the Premier', N'PREM', 1, N'', N'', N'', CAST(N'2016-10-27T19:30:07.973' AS DateTime), N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'', N'', NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, N'')

INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (N'e6177ccb-93ec-4ab5-a75c-f795337a39cf', N'E6177CCB-93EC-4AB5-A75C-F795337A39CF', 1, N'Citizen Engagement', N'CITENG', 1, N'', N'', N'', CAST(N'2016-10-27T19:30:07.973' AS DateTime), N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'', N'', NULL, NULL, NULL, NULL, N'', NULL, NULL, NULL, N'')

INSERT [dbo].[Sector] ( [Key], [SortOrder], [IsActive], [DisplayName], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId]) VALUES ( N'government-operations', 0, 1, N'Government Operations', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL)

INSERT [dbo].[Theme] ([Key], [DisplayName], [Timestamp], [TopReleaseId], [FeatureReleaseId], [SortOrder], [IsActive]) VALUES (N'health', N'Health', CURRENT_TIMESTAMP, NULL, NULL, 0, 1)

INSERT [dbo].[Service] ([Key], [DisplayName], [SortOrder], [IsActive]) VALUES (N'municipalities', N'Municipalities', 0, 1)

INSERT [dbo].[Language] ([Id], [SortOrder], [Name]) VALUES (3084, 1, N'French')
INSERT [dbo].[Language] ([Id], [SortOrder], [Name]) VALUES (4105, 0, N'English')

INSERT [dbo].[MediaDistributionList] ([Id], [Key], [DisplayName], [SortOrder], [IsActive]) VALUES (NEWID(), N'budget', N'BUDGET', 0, 1);

INSERT [dbo].[NewsReleaseCollection] ([Id], [Name]) VALUES (N'42c50941-64db-41b7-8fda-94d7f7aa9ae1', N'2009-2013')
INSERT [dbo].[NewsReleaseCollection] ([Id], [Name]) VALUES (N'37e637e3-0a3a-45f7-82f1-feb94dcef00a', N'2013-2017')
INSERT [dbo].[NewsReleaseCollection] ([Id], [Name]) VALUES (N'42ae17e6-5a27-4f76-ba10-2d42dbc1c358', N'2017-2017')
INSERT [dbo].[NewsReleaseCollection] ([Id], [Name]) VALUES (N'dd1be731-8c9a-4f50-953d-b8db37f85d17', N'2017-2021')

-- NB Ministries/Departments
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'aboriginal-affairs', 15, N'Department of Aboriginal Affairs', N'AAS', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'agriculture-aquaculture-and-fisheries', 20, N'Department of Agriculture, Aquaculture and Fisheries', N'AAF', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'department-of-seniors', 24, N'Department of Seniors', N'SENIORS', 0, N'', N'-', N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'economic-development-small-business', 20, N'Department of Economic Development and Small Business', N'EDSB', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'education-early-childhood-development', 30, N'Department of Education and Early Childhood Development', N'EECD', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'energy-resource-development', 40, N'Department of Energy and Resource Development', N'ERD', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'environment-local-government', 10, N'Department of Environment and Local Government', N'ELG', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'executive-council', 5, N'Executive Council Office', N'ECO', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'finance', 50, N'Department of Finance', N'FIN', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'health', 60, N'Department of Health', N'DH', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'intergovernmental-affairs', 70, N'Department of Intergovernmental Affairs', N'IGA', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'justice-attorney-general', 80, N'Department of Justice and Office of the Attorney General', N'JAG', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'post-secondary-education-training-labour', 90, N'Department of Post-Secondary Education, Training and Labour', N'PETL', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'public-safety', 100, N'Department of Public Safety', N'DPS', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'service-new-brunswick', 200, N'Department of Service New Brunswick', N'SERVICE', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'social-development', 110, N'Department of Social Development', N'SD', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'tourism-heritage-culture', 120, N'Department of Tourism, Heritage and Culture', N'THC', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[Ministry] ([Id], [Key], [SortOrder], [DisplayName], [Abbreviation], [IsActive], [MinisterEmail], [MinisterPhotoUrl], [MinisterPageHtml], [Timestamp], [MiscHtml], [MiscRightHtml], [TwitterUsername], [FlickrUrl], [YoutubeUrl], [AudioUrl], [FacebookEmbedHtml], [YoutubeEmbedHtml], [AudioEmbedHtml], [TopReleaseId], [FeatureReleaseId], [MinisterAddress], [MinisterName], [MinisterSummary], [MinistryUrl], [ParentId], [ContactUserId], [SecondContactUserId], [WeekendContactNumber], [EodFinalizedDateTime], [EodLastRunUserId], [EodLastRunDateTime], [DisplayAdditionalName]) VALUES (NEWID(), N'transportation-infrastructure', 130, N'Department of Transportation and Infrastructure', N'DTI', 1, N'', NULL, N'', CURRENT_TIMESTAMP, N'', N'', N'', N'', N'', N'', N'', N'', N'', NULL, NULL, N'', N'-', N'-', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO


-- insert ministry sectors...
INSERT INTO [dbo].[MinistrySector]
	  SELECT m.id, s.id from dbo.Ministry m, dbo.Sector s;

-- insert ministry language here... just seed with english... (4105)
insert into dbo.MinistryLanguage
  select m.id, 4105, m.DisplayName from dbo.Ministry m;

-- insert sector language here... just seed with english... (4105)
insert into dbo.SectorLanguage
  select s.id, 4105,s.DisplayName from dbo.Sector s;
  
GO


INSERT INTO [dbo].[MediaRequestResolution]([Id],[DisplayAs]) VALUES (NEWID(), N'Provided Background')
INSERT INTO [dbo].[MediaRequestResolution]([Id],[DisplayAs]) VALUES (NEWID(), N'Provided Statement')
INSERT INTO [dbo].[MediaRequestResolution]([Id],[DisplayAs]) VALUES (NEWID(), N'Scheduled Interview')
INSERT INTO [dbo].[MediaRequestResolution]([Id],[DisplayAs]) VALUES (NEWID(), N'Referred to Third Party')
INSERT INTO [dbo].[MediaRequestResolution]([Id],[DisplayAs]) VALUES (NEWID(), N'Photo-Op')
INSERT INTO [dbo].[MediaRequestResolution]([Id],[DisplayAs]) VALUES (NEWID(), N'Reporter Dropped')
INSERT INTO [dbo].[MediaRequestResolution]([Id],[DisplayAs]) VALUES (NEWID(), N'Declined to Comment')
INSERT INTO [dbo].[MediaRequestResolution]([Id],[DisplayAs]) VALUES (NEWID(), N'Unavailable for Interview')

GO

INSERT INTO [dbo].[ApplicationSetting]([SettingName] ,[SettingValue]) VALUES ('live_webcast_enabled' ,'false')
GO

INSERT INTO [dbo].[Carousel] ([Id] ,[PublishDateTime], [Timestamp]) VALUES  (NEWID() ,CURRENT_TIMESTAMP ,CURRENT_TIMESTAMP)
GO