//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorporateCalendar.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTheme
    {
        public int ActivityId { get; set; }
        public System.Guid ThemeId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime LastUpdatedDateTime { get; set; }
        public int LastUpdatedBy { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
