//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorporateCalendar.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LegacyCalendarEntities : DbContext
    {
        public LegacyCalendarEntities()
            : base("name=LegacyCalendarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityCategory> ActivityCategories { get; set; }
        public virtual DbSet<ActivityCommunicationMaterial> ActivityCommunicationMaterials { get; set; }
        public virtual DbSet<ActivityFilter> ActivityFilters { get; set; }
        public virtual DbSet<ActivityNROrigin> ActivityNROrigins { get; set; }
        public virtual DbSet<ActivitySector> ActivitySectors { get; set; }
        public virtual DbSet<ActivitySharedWith> ActivitySharedWiths { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CommunicationContact> CommunicationContacts { get; set; }
        public virtual DbSet<CommunicationMaterial> CommunicationMaterials { get; set; }
        public virtual DbSet<EventPlanner> EventPlanners { get; set; }
        public virtual DbSet<GovernmentRepresentative> GovernmentRepresentatives { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<NewsFeed> NewsFeeds { get; set; }
        public virtual DbSet<NRDistribution> NRDistributions { get; set; }
        public virtual DbSet<NROrigin> NROrigins { get; set; }
        public virtual DbSet<PremierRequested> PremierRequesteds { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<SystemUserMinistry> SystemUserMinistries { get; set; }
        public virtual DbSet<Videographer> Videographers { get; set; }
        public virtual DbSet<ActivityTheme> ActivityThemes { get; set; }
        public virtual DbSet<ActivityKeyword> ActivityKeywords { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<ActivityInitiative> ActivityInitiatives { get; set; }
        public virtual DbSet<Initiative> Initiatives { get; set; }
        public virtual DbSet<ActivityFile> ActivityFiles { get; set; }
        public virtual DbSet<Ministry> Ministries { get; set; }
        public virtual DbSet<Sector> Sectors { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
    }
}
